default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: checkplant_test_development

test:
  <<: *default
  database: checkplant_test_test

production:
  <<: *default
  database: checkplant_test_production
  username: checkplant_test
  password: <%= ENV["CHECKPLANT_TEST_DATABASE_PASSWORD"] %>
