default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: checkplants_development

test:
  <<: *default
  database: checkplants_test

production:
  <<: *default
  database: checkplants_production
  username: checkplants
  password: <%= ENV["CHECKPLANTS_DATABASE_PASSWORD"] %>
